### PR TITLE
account creation with encryption support

### PR DESCRIPTION
**Pull request by fgfm999**
Hi
I re-implement account creation and import with encryption. Please take a look, thanks.
1. As you mentioned before, `Account` needs to work with various lock designs.`. I introduce  `Secret` and `Public` key abstraction, but it seems impossible to work with other ckb libraries without exporting the underlying secp256k1 key 
2. The account encryption and decryption are almost as same as the `ckb-cli`. Maybe this logic could be in the `ckb-sdk` in the future

### CODE REVIEW

**Comment by pLabarta** [comment]
Hello again! Great to see you've been working towards supporting different locks.
I'll review these additions and then move the `account` module to the `sdk` lib before merging.

**Comment by pLabarta** [comment]
Aside from the dependency version compile error, I found no other issues.

This is ready to merge after fixing it.

Great work!

**Comment by fgfm999** [comment]
@pLabarta thanks for your review.  could you  show me the `the dependency version compile error`, so I can fix it.

**Comment by pLabarta** [comment]
Yes, commented on the code but if tou can't see it, I'll copy it here:

Currently, this branch has a compile error caused by the ckb-fixed-hash.

error: failed to compile `trampoline v0.1.0 (/home/p/IAMM/account-fork/trampoline)`, intermediate artifacts can be found at `/home/p/IAMM/account-fork/trampoline/target`

Caused by:
  failed to select a version for the requirement `ckb-fixed-hash = "^0.102.0"`
  candidate versions found which didn't match: 0.103.0, 0.101.8, 0.101.7, ...
  location searched: crates.io index
  required by package `trampoline-sdk v0.1.0 (/home/p/IAMM/account-fork/trampoline/sdk)`
      ... which satisfies path dependency `trampoline-sdk` of package `trampoline v0.1.0 (/home/p/IAMM/account-fork/trampoline)`
Bumping ckb-fixed-hash version to 0.103.0 fixes this problem and compilation exits with success.

**Pull request merged**
